In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [15]:
#We are creating really high values so we can show case how its harder for Gradient decent to
np.random.seed(59)
X = np.random.randint(0,1000000,(50000,5))
weights = np.array([-69,4,28,67,74])
bias = 987
y = np.dot(X,weights) + bias


In [16]:
#Checking our data
print(X.shape)
print(X[:5,:])
print(y.shape)
print(y)

(50000, 5)
[[889009 744876 668877 918167 927083]
 [678095 741173 645177 375168 911199]
 [865347 119104 760403 535031  66861]
 [ 33758 415705 696752 787273 229012]
 [286437 998466 368246 334113 857291]]
(50000,)
[ 90488757  66807062   2854535 ...  16161166 115690186  83172750]


In [19]:
class LineraRegression:
  def __init__(self,learning_rate = 0.1,max_iterations=10000):
    self.lr = learning_rate
    self.max_itr = max_iterations
    self.weights = None
    self.bias = None
    self.loss_history = []

  def fit(self,X,y):
    #lets initialize weights first
    n_samples , n_features = X.shape
    self.weights = np.zeros(n_features)
    self.bias = 0
    for epoch in range(self.max_itr):
      y_pred = self.predict(X)
      error = y_pred - y
      dw = 2/n_samples * np.dot(X.T,error)
      db = 2/n_samples * np.sum(error)
      self.weights = self.weights - self.lr*dw
      self.bias = self.bias -self.lr*db
      loss = np.mean(error**2)
      self.loss_history.append(np.mean(error**2))
      if epoch % 1000 == 0 :
        print(f"Epoch {epoch} , Loss {loss}")
  def predict(self,X):
    return np.dot(X,self.weights) + self.bias


In [21]:
model = LineraRegression(learning_rate=0.00001)
model.fit(X,y)

Epoch 0 , Loss 3986933616990935.0


/tmp/ipython-input-600002137.py:21: RuntimeWarning: overflow encountered in square
  loss = np.mean(error**2)
/tmp/ipython-input-600002137.py:22: RuntimeWarning: overflow encountered in square
  self.loss_history.append(np.mean(error**2))
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/tmp/ipython-input-600002137.py:19: RuntimeWarning: invalid value encountered in subtract
  self.weights = self.weights - self.lr*dw
/tmp/ipython-input-600002137.py:20: RuntimeWarning: invalid value encountered in scalar subtract
  self.bias = self.bias -self.lr*db


Epoch 1000 , Loss nan
Epoch 2000 , Loss nan
Epoch 3000 , Loss nan
Epoch 4000 , Loss nan
Epoch 5000 , Loss nan
Epoch 6000 , Loss nan
Epoch 7000 , Loss nan
Epoch 8000 , Loss nan
Epoch 9000 , Loss nan


As you can see our data vales are too high, and python throws as overflow error because our values become too large, there is a solution for this which is Scaling, so now we will scale out data using a StandardScaler method.

In [ ]:
class StandardScalar:
  def __init__(self,):
    pass